spring:
  profiles:
    active: dev
  aop:
    auto: true
server:
  port: 8088
  servlet:
    context-path: /wechat
wechat:
  appId: wx52a5971ec687ccc9
  appSecret: a5da7b3fc168e5f9cbf26419f099a2c7
mybatis:
  mapper-locations: classpath*:mapper/*.xml

